stages:
- build

Build:
  stage: build
  script:
    - cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Release
    - cmake --build build
  artifacts:
    name: "avpn"
    paths:
      - build/bin/avpn
    expire_in: 5 day
