namespace avpn;

enum pkt_type : byte {
	pt_tcp = 0,			// 原始的tcp ip包.
	pt_udp,				// 原始的udp ip包.
	pt_fec,				// Fec数据包, 指示包为FecMessageParity.
	pt_ctrl,			// 控制数据包.

	// 认证数据包, 认证方法: google auth code, client配置secret和对
	// 应的client id, 生成auth code及client id并发送到server, server
	// 根据client id找到 secret 并生成 google auth code 进行比对并
	// 返回成功或失败消息.
	pt_auth,
}

table AuthMessage {
	cliend_id: string;	// 客户端id.
	auth_code: int;		// google auth code.
}

table AuthMessageReply {
	virtual_ipaddr: string;	// server分配的虚拟ip.
	error: string;	// 错误, 出错时将提示详细的错误信息.
}

table FecMessage {
	pid: ubyte;		// 包id, 在组中的id.
	gid: long;		// group id.
	gsize: int;		// group 大小, 字节数.
	ds: ubyte;		// data shards.
	ps: ubyte;		// parity shards.
}

table Message {
	type: pkt_type;			// 包类型.
	content: [ubyte];		// 用于包含大量数据的字段, 如ip包.

	fec_pkt: FecMessage;		// fec包.

	auth: AuthMessage;		// 认证数据包.
	auth_reply: AuthMessageReply;	// 认证回复数据包.
}

root_type Message;
