// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PTVPN_AVPN_H_
#define FLATBUFFERS_GENERATED_PTVPN_AVPN_H_

#include "flatbuffers/flatbuffers.h"

namespace avpn {

struct message;
struct messageBuilder;
struct messageT;

enum class pkt_type : int8_t {
  pt_tcp = 0,
  pt_udp = 1,
  pt_ctrl = 2,
  MIN = pt_tcp,
  MAX = pt_ctrl
};

inline const pkt_type (&EnumValuespkt_type())[3] {
  static const pkt_type values[] = {
    pkt_type::pt_tcp,
    pkt_type::pt_udp,
    pkt_type::pt_ctrl
  };
  return values;
}

inline const char * const *EnumNamespkt_type() {
  static const char * const names[4] = {
    "pt_tcp",
    "pt_udp",
    "pt_ctrl",
    nullptr
  };
  return names;
}

inline const char *EnumNamepkt_type(pkt_type e) {
  if (flatbuffers::IsOutRange(e, pkt_type::pt_tcp, pkt_type::pt_ctrl)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamespkt_type()[index];
}

struct messageT : public flatbuffers::NativeTable {
  typedef message TableType;
  avpn::pkt_type type = avpn::pkt_type::pt_tcp;
  int64_t pkt_dd = 0;
  int64_t pkt_group_dd = 0;
  uint16_t data_shards = 0;
  uint16_t parity_shards = 0;
  std::string content{};
};

struct message FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef messageT NativeTableType;
  typedef messageBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_PKT_DD = 6,
    VT_PKT_GROUP_DD = 8,
    VT_DATA_SHARDS = 10,
    VT_PARITY_SHARDS = 12,
    VT_CONTENT = 14
  };
  avpn::pkt_type type() const {
    return static_cast<avpn::pkt_type>(GetField<int8_t>(VT_TYPE, 0));
  }
  int64_t pkt_dd() const {
    return GetField<int64_t>(VT_PKT_DD, 0);
  }
  int64_t pkt_group_dd() const {
    return GetField<int64_t>(VT_PKT_GROUP_DD, 0);
  }
  uint16_t data_shards() const {
    return GetField<uint16_t>(VT_DATA_SHARDS, 0);
  }
  uint16_t parity_shards() const {
    return GetField<uint16_t>(VT_PARITY_SHARDS, 0);
  }
  const flatbuffers::String *content() const {
    return GetPointer<const flatbuffers::String *>(VT_CONTENT);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE) &&
           VerifyField<int64_t>(verifier, VT_PKT_DD) &&
           VerifyField<int64_t>(verifier, VT_PKT_GROUP_DD) &&
           VerifyField<uint16_t>(verifier, VT_DATA_SHARDS) &&
           VerifyField<uint16_t>(verifier, VT_PARITY_SHARDS) &&
           VerifyOffset(verifier, VT_CONTENT) &&
           verifier.VerifyString(content()) &&
           verifier.EndTable();
  }
  messageT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(messageT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<message> Pack(flatbuffers::FlatBufferBuilder &_fbb, const messageT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct messageBuilder {
  typedef message Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_type(avpn::pkt_type type) {
    fbb_.AddElement<int8_t>(message::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_pkt_dd(int64_t pkt_dd) {
    fbb_.AddElement<int64_t>(message::VT_PKT_DD, pkt_dd, 0);
  }
  void add_pkt_group_dd(int64_t pkt_group_dd) {
    fbb_.AddElement<int64_t>(message::VT_PKT_GROUP_DD, pkt_group_dd, 0);
  }
  void add_data_shards(uint16_t data_shards) {
    fbb_.AddElement<uint16_t>(message::VT_DATA_SHARDS, data_shards, 0);
  }
  void add_parity_shards(uint16_t parity_shards) {
    fbb_.AddElement<uint16_t>(message::VT_PARITY_SHARDS, parity_shards, 0);
  }
  void add_content(flatbuffers::Offset<flatbuffers::String> content) {
    fbb_.AddOffset(message::VT_CONTENT, content);
  }
  explicit messageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<message>(end);
    return o;
  }
};

inline flatbuffers::Offset<message> Createmessage(
    flatbuffers::FlatBufferBuilder &_fbb,
    avpn::pkt_type type = avpn::pkt_type::pt_tcp,
    int64_t pkt_dd = 0,
    int64_t pkt_group_dd = 0,
    uint16_t data_shards = 0,
    uint16_t parity_shards = 0,
    flatbuffers::Offset<flatbuffers::String> content = 0) {
  messageBuilder builder_(_fbb);
  builder_.add_pkt_group_dd(pkt_group_dd);
  builder_.add_pkt_dd(pkt_dd);
  builder_.add_content(content);
  builder_.add_parity_shards(parity_shards);
  builder_.add_data_shards(data_shards);
  builder_.add_type(type);
  return builder_.Finish();
}

struct message::Traits {
  using type = message;
  static auto constexpr Create = Createmessage;
};

inline flatbuffers::Offset<message> CreatemessageDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    avpn::pkt_type type = avpn::pkt_type::pt_tcp,
    int64_t pkt_dd = 0,
    int64_t pkt_group_dd = 0,
    uint16_t data_shards = 0,
    uint16_t parity_shards = 0,
    const char *content = nullptr) {
  auto content__ = content ? _fbb.CreateString(content) : 0;
  return avpn::Createmessage(
      _fbb,
      type,
      pkt_dd,
      pkt_group_dd,
      data_shards,
      parity_shards,
      content__);
}

flatbuffers::Offset<message> Createmessage(flatbuffers::FlatBufferBuilder &_fbb, const messageT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline messageT *message::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<messageT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void message::UnPackTo(messageT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = type(); _o->type = _e; }
  { auto _e = pkt_dd(); _o->pkt_dd = _e; }
  { auto _e = pkt_group_dd(); _o->pkt_group_dd = _e; }
  { auto _e = data_shards(); _o->data_shards = _e; }
  { auto _e = parity_shards(); _o->parity_shards = _e; }
  { auto _e = content(); if (_e) _o->content = _e->str(); }
}

inline flatbuffers::Offset<message> message::Pack(flatbuffers::FlatBufferBuilder &_fbb, const messageT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return Createmessage(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<message> Createmessage(flatbuffers::FlatBufferBuilder &_fbb, const messageT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const messageT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _type = _o->type;
  auto _pkt_dd = _o->pkt_dd;
  auto _pkt_group_dd = _o->pkt_group_dd;
  auto _data_shards = _o->data_shards;
  auto _parity_shards = _o->parity_shards;
  auto _content = _o->content.empty() ? 0 : _fbb.CreateString(_o->content);
  return avpn::Createmessage(
      _fbb,
      _type,
      _pkt_dd,
      _pkt_group_dd,
      _data_shards,
      _parity_shards,
      _content);
}

inline const avpn::message *Getmessage(const void *buf) {
  return flatbuffers::GetRoot<avpn::message>(buf);
}

inline const avpn::message *GetSizePrefixedmessage(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<avpn::message>(buf);
}

inline bool VerifymessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<avpn::message>(nullptr);
}

inline bool VerifySizePrefixedmessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<avpn::message>(nullptr);
}

inline void FinishmessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<avpn::message> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedmessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<avpn::message> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<avpn::messageT> UnPackmessage(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<avpn::messageT>(Getmessage(buf)->UnPack(res));
}

inline std::unique_ptr<avpn::messageT> UnPackSizePrefixedmessage(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<avpn::messageT>(GetSizePrefixedmessage(buf)->UnPack(res));
}

}  // namespace avpn

#endif  // FLATBUFFERS_GENERATED_PTVPN_AVPN_H_
