add_custom_target(AvpnUnitTests)
set_target_properties(AvpnUnitTests PROPERTIES FOLDER "AVPN tests")

set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -DENABLE_LOGGER")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -DENABLE_LOGGER -DDISABLE_LOGGER_TO_CONSOLE -DLOGGER_DBG_VIEW")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} -DENABLE_LOGGER -DDISABLE_LOGGER_TO_CONSOLE -DLOGGER_DBG_VIEW")
set(CMAKE_CXX_FLAGS_MINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL} -DENABLE_LOGGER -DDISABLE_LOGGER_TO_CONSOLE -DLOGGER_DBG_VIEW")

add_subdirectory(fec_cache)
#add_subdirectory(network_test)
#add_subdirectory(reedsolomon)
#add_subdirectory(mimalloc)
#add_subdirectory(acl)
#add_subdirectory(crypto)
#add_subdirectory(protocol)
#
#find_library(SYSTEMD_LIB systemd)
#if (SYSTEMD_LIB)
#add_subdirectory(dbustest)
#endif()
#
#if (MSVC)
#	if (ENABLE_USE_WINTUN)
#		add_subdirectory(wintun)
#	endif()
#endif()
