/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.jackarain;

public class LogCallback {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected LogCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LogCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        xavpnJNI.delete_LogCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    xavpnJNI.LogCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    xavpnJNI.LogCallback_change_ownership(this, swigCPtr, true);
  }

  public void onLog(long time, LogLevel level, String message) {
    xavpnJNI.LogCallback_onLog(swigCPtr, this, time, level.swigValue(), message);
  }

  @SuppressWarnings("this-escape")
  public LogCallback() {
    this(xavpnJNI.new_LogCallback(), true);
    xavpnJNI.LogCallback_director_connect(this, swigCPtr, true, true);
  }

}
