/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.jackarain;

public final class LogLevel {
  public final static LogLevel DEBUG = new LogLevel("DEBUG", xavpnJNI.LogLevel_DEBUG_get());
  public final static LogLevel INFO = new LogLevel("INFO", xavpnJNI.LogLevel_INFO_get());
  public final static LogLevel WARN = new LogLevel("WARN", xavpnJNI.LogLevel_WARN_get());
  public final static LogLevel ERROR = new LogLevel("ERROR", xavpnJNI.LogLevel_ERROR_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LogLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LogLevel.class + " with value " + swigValue);
  }

  private LogLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LogLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LogLevel(String swigName, LogLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LogLevel[] swigValues = { DEBUG, INFO, WARN, ERROR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

