/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.jackarain;

public class ProtectCallback {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected ProtectCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProtectCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        xavpnJNI.delete_ProtectCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    xavpnJNI.ProtectCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    xavpnJNI.ProtectCallback_change_ownership(this, swigCPtr, true);
  }

  public boolean onProtect(int fd) {
    return xavpnJNI.ProtectCallback_onProtect(swigCPtr, this, fd);
  }

  @SuppressWarnings("this-escape")
  public ProtectCallback() {
    this(xavpnJNI.new_ProtectCallback(), true);
    xavpnJNI.ProtectCallback_director_connect(this, swigCPtr, true, true);
  }

}
